<div class="image-seller">
	<div class="row-s">
		<div class="col-md-6 col-sm-12 one">
			<img class="thumb-a" src="<?php echo $block->getViewFileUrl('images/ads1.jpg'); ?>" />
			<div class="text">
				<p>autumn</p>
				<p id="coll">collection</p>
				<p id="boldd">new accessories</p>
			</div>
			<div class="label">
				<div class="label-title">NEW</div>
				<div id="label-round"></div>
			</div>
		</div>
		<div class="col-md-3 col-sm-6 two">
			<img  class="thumb" src="<?php echo $block->getViewFileUrl('images/ads2.jpg'); ?>" />
			<div class="text">
				<p id="women">women's</p>
				<p id="fashion">fashion</p>
			</div>
		</div>
		<div class="col-md-3 col-sm-6 three">
			<div class="first">
				<img class="anh-a" src="<?php echo $block->getViewFileUrl('images/ads3.jpg'); ?>" />
				<div class="labels">
					<div class="labels-title">-25%</div>
					<div id="labels-round"></div> 
				</div>
			</div>
			<div class="second">
				<img class="anh-b" src="<?php echo $block->getViewFileUrl('images/ads4.jpg'); ?>" />
				<div class="text">
					<p id="shoe">casual shoes</p>
					<p id="limit">limited & unique</p>
				</div>
			</div>
		</div>
		
	</div>
</div>